// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfLT2e8136nd447n04CaRxEo1reV3JsEY',
    appId: '1:733025330061:web:51d56e89f29edf8a8a53c4',
    messagingSenderId: '733025330061',
    projectId: 'my-wallet-f2eb2',
    authDomain: 'my-wallet-f2eb2.firebaseapp.com',
    storageBucket: 'my-wallet-f2eb2.appspot.com',
    measurementId: 'G-SP948SR5L4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmv9sbkrC8XcpkDa7ATiXRP2o_A7dSFhM',
    appId: '1:733025330061:android:f9584661b185a51b8a53c4',
    messagingSenderId: '733025330061',
    projectId: 'my-wallet-f2eb2',
    storageBucket: 'my-wallet-f2eb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOyfGRLG7RL5bBG5xeJmIIhRfG2Y2BexA',
    appId: '1:733025330061:ios:82abb461450ccfc48a53c4',
    messagingSenderId: '733025330061',
    projectId: 'my-wallet-f2eb2',
    storageBucket: 'my-wallet-f2eb2.appspot.com',
    iosClientId: '733025330061-jggd6k8r3ajja4cnddu0jrefek2rakd0.apps.googleusercontent.com',
    iosBundleId: 'com.example.myWallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOyfGRLG7RL5bBG5xeJmIIhRfG2Y2BexA',
    appId: '1:733025330061:ios:2c1e1e30d466b7688a53c4',
    messagingSenderId: '733025330061',
    projectId: 'my-wallet-f2eb2',
    storageBucket: 'my-wallet-f2eb2.appspot.com',
    iosClientId: '733025330061-rjkkf9t4vc6qhpemtgpve0pobmck65i9.apps.googleusercontent.com',
    iosBundleId: 'com.example.myWallet.RunnerTests',
  );
}
